name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CI Environment
        uses: yetanalytics/action-setup-env@v1.0.0
        with:
          java-version: "11"
          java-distribution: "temurin"
          node-version: "16"
          clojure-version: "1.11.1.1165"

      - name: Run make target ${{ matrix.target }}
        run: make ${{ matrix.target }}
